"""OIDC client snippet generation for Authelia.

This module generates OIDC client configuration snippets that are installed
to /etc/halos/oidc-clients.d/ and merged by Authelia's prestart script.
"""

from typing import Any

import yaml


def generate_oidc_snippet(metadata: dict[str, Any]) -> str | None:
    """Generate OIDC client snippet for Authelia.

    Args:
        metadata: Package metadata dictionary

    Returns:
        YAML content for OIDC client snippet, or None if not an OIDC app
    """
    traefik_config = metadata.get("traefik")
    if not traefik_config:
        return None

    if traefik_config.get("auth") != "oidc":
        return None

    oidc_config = traefik_config.get("oidc")
    if not oidc_config:
        return None

    app_id = metadata.get("app_id", "")
    package_name = metadata.get("package_name", "")

    # Get redirect path and ensure it starts with /
    redirect_path = oidc_config.get("redirect_path", "/callback")
    if not redirect_path.startswith("/"):
        redirect_path = "/" + redirect_path

    # Build redirect URIs. The reverse proxy's prestart script in
    # halos-core-containers expands ${HALOS_DOMAIN} across every configured
    # hostname at runtime (halos_expand_oidc_redirect_uri), so each entry here
    # becomes one entry per hostname in the merged oidc-clients.yml.
    redirect_uris = [
        f"http://${{HALOS_DOMAIN}}{redirect_path}",
        f"https://${{HALOS_DOMAIN}}{redirect_path}",
    ]

    # Build snippet content
    snippet = {
        "client_id": app_id,
        "client_name": oidc_config.get("client_name"),
        "client_secret_file": f"/var/lib/container-apps/{package_name}/data/oidc-secret",
        "redirect_uris": redirect_uris,
        "scopes": oidc_config.get("scopes", ["openid", "profile", "email"]),
        "consent_mode": oidc_config.get("consent_mode", "implicit"),
    }

    # Generate YAML with header comments
    lines = [
        f"# OIDC client configuration for {app_id}",
        "# Generated by container-packaging-tools",
        f"# Installed to /etc/halos/oidc-clients.d/{app_id}.yml",
        "",
        yaml.dump(snippet, default_flow_style=False, sort_keys=False),
    ]

    return "\n".join(lines)
