"""Prestart script generation for container apps."""

from typing import Any

from generate_container_packages.labels import find_port_env_var
from generate_container_packages.loader import AppDefinition
from generate_container_packages.oidc_snippet import generate_oidc_section


def get_homarr_url_expression(
    web_ui: dict[str, Any], default_config: dict[str, str] | None
) -> str | None:
    """Generate the HOMARR_URL shell expression.

    Args:
        web_ui: Web UI configuration dictionary
        default_config: Default configuration dictionary

    Returns:
        Shell expression for HOMARR_URL, or None if web_ui is disabled
    """
    if not web_ui or not web_ui.get("enabled", False):
        return None

    protocol = web_ui.get("protocol", "http")
    port = web_ui.get("port", 80)
    path = web_ui.get("path", "")

    # Find port environment variable
    port_var = find_port_env_var(default_config)

    # Build port expression
    if port_var:
        port_expr = f"${{{port_var}:-{port}}}"
    else:
        port_expr = str(port)

    # Build URL expression. HALOS_DOMAIN is inherited from the unit environment
    # (the halos-resolve-domain producer publishes it via /run/halos/domain.env),
    # so the generated prestart no longer resolves or hardcodes the hostname.
    url = f"{protocol}://${{HALOS_DOMAIN}}:{port_expr}"
    if path and path != "/":
        # Ensure path starts with /
        if not path.startswith("/"):
            path = "/" + path
        url += path

    return url


def generate_prestart_script(app_def: AppDefinition) -> str:
    """Generate prestart script content for a container app.

    The prestart script:
    1. Creates the runtime env directory and runtime.env (mode 600 before any write)
    2. Loads existing env files to access config values
    3. Computes HOMARR_URL when web_ui is enabled; HALOS_DOMAIN is inherited from
       the unit environment, not resolved here
    4. Appends computed values to runtime.env
    5. Sources an optional app-prestart.sh hook for app-specific logic

    Args:
        app_def: Application definition

    Returns:
        Bash script content as string
    """
    metadata = app_def.metadata
    package_name = metadata.get("package_name", "unknown")
    web_ui = metadata.get("web_ui", {})
    default_config = metadata.get("default_config", {})

    # Paths
    etc_dir = f"/etc/container-apps/{package_name}"
    run_dir = f"/run/container-apps/{package_name}"
    lib_dir = f"/var/lib/container-apps/{package_name}"
    runtime_env = f"{run_dir}/runtime.env"
    app_prestart = f"{lib_dir}/app-prestart.sh"

    # Build script
    lines = [
        "#!/bin/bash",
        f"# Prestart script for {package_name}",
        "# Auto-generated by container-packaging-tools",
        "set -e",
        "",
        "# Create runtime directory and runtime.env. The file is created mode 600",
        "# before any write, so the mode predates content and survives appends.",
        f'RUNTIME_ENV="{runtime_env}"',
        'mkdir -p "$(dirname "$RUNTIME_ENV")"',
        'install -m 600 /dev/null "$RUNTIME_ENV"',
        "",
        "# Load config values from env files",
        "set -a",
        f'[ -f "{etc_dir}/env.defaults" ] && . "{etc_dir}/env.defaults"',
        f'[ -f "{etc_dir}/env" ] && . "{etc_dir}/env"',
        "set +a",
    ]

    # Add HOMARR_URL if web_ui is enabled
    homarr_url_expr = get_homarr_url_expression(web_ui, default_config)
    if homarr_url_expr:
        lines.extend(
            [
                "",
                "# Compute Homarr URL (HALOS_DOMAIN inherited from the unit environment)",
                f'HOMARR_URL="{homarr_url_expr}"',
                'echo "HOMARR_URL=$HOMARR_URL" >> "$RUNTIME_ENV"',
            ]
        )

    # OIDC client registration for native-OAuth apps (routing.auth.mode: oidc).
    # The client secret is provisioned once by postinst; this section reads it,
    # resolves the external port (port-based redirects), appends the container's
    # OIDC env vars, and writes the Authelia client snippet.
    routing = metadata.get("routing") or {}
    auth = routing.get("auth") if isinstance(routing, dict) else {}
    auth = auth if isinstance(auth, dict) else {}
    oidc = auth.get("oidc")
    # Gate on mode == "oidc" to stay consistent with is_oidc_app, which drives the
    # postinst secret provisioning and the Authelia unit ordering.
    if auth.get("mode") == "oidc" and oidc:
        app_id = metadata.get("app_id", package_name)
        lines.extend(generate_oidc_section(oidc, app_id, package_name))

    # Source the optional app-specific hook last, with the framework scaffolding
    # (sourced env, $HALOS_DOMAIN, $RUNTIME_ENV) already in place. Absence is a
    # no-op; the hook must append to $RUNTIME_ENV, never truncate it.
    lines.extend(
        [
            "",
            "# Run app-specific prestart hook if present",
            f'[ -f "{app_prestart}" ] && . "{app_prestart}"',
        ]
    )

    # Final newline
    lines.append("")

    return "\n".join(lines)
